// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-U94NV7T
// DateTime: 25.09.2015 0:16:56
// UserName: jedik
// Input file <SimpleYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using ProgramTree;

namespace SimpleParser
{
public enum Tokens {
    error=1,EOF=2,BEGIN=3,END=4,CYCLE=5,ASSIGN=6,
    SEMICOLON=7,LEFT_R_BRACKET=8,RIGHT_R_BRACKET=9,IF=10,ELSE=11,FOR=12,
    CIN=13,COUT=14,ENDL=15,DO=16,PLUS=17,MINUS=18,
    MULT=19,DIV=20,MORE=21,LESS=22,MORE_EQUAL=23,LESS_EQUAL=24,
    SHIFT_LEFT=25,SHIFT_RIGHT=26,INUM=27,RNUM=28,ID=29};

public struct ValueType
{ 
			public double dVal; 
			public int iVal; 
			public string sVal; 
			public Node nVal;
			public ExprNode eVal;
			public StatementNode stVal;
			public BlockNode blVal;
			public BinExprNode bExprVal;
			public ConditionNode condVal;
      public ForCycleNode forVal;
      public PrintNode printVal;
      public ExprListNode exprlVal;
       }
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SimpleYacc.y
// Эти объявления добавляются в класс GPPGParser, представляющий собой парсер, генерируемый системой gppg
    public BlockNode root; // Корневой узел синтаксического дерева 
    public Parser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[37];
  private static State[] states = new State[80];
  private static string[] nonTerms = new string[] {
      "expr", "ident", "assign", "statement", "cycle", "stlist", "block", "binmult", 
      "binsum", "bincond", "cond", "for_cycle", "print_expr", "print_expr_list", 
      "progr", "$accept", };

  static Parser() {
    states[0] = new State(new int[]{3,4},new int[]{-15,1,-7,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-6,5,-4,79,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[5] = new State(new int[]{4,6,29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-4,7,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[6] = new State(-34);
    states[7] = new State(-4);
    states[8] = new State(new int[]{7,9});
    states[9] = new State(-5);
    states[10] = new State(new int[]{6,11});
    states[11] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-10,12,-9,38,-8,30,-1,29,-2,19});
    states[12] = new State(new int[]{21,13,22,31,23,33,24,35,7,-18,9,-18});
    states[13] = new State(new int[]{29,20,27,21,8,22},new int[]{-9,14,-8,30,-1,29,-2,19});
    states[14] = new State(new int[]{17,15,18,25,21,-19,22,-19,23,-19,24,-19,7,-19,9,-19,25,-19});
    states[15] = new State(new int[]{29,20,27,21,8,22},new int[]{-8,16,-1,29,-2,19});
    states[16] = new State(new int[]{19,17,20,27,17,-25,18,-25,21,-25,22,-25,23,-25,24,-25,7,-25,9,-25,25,-25});
    states[17] = new State(new int[]{29,20,27,21,8,22},new int[]{-1,18,-2,19});
    states[18] = new State(-28);
    states[19] = new State(-31);
    states[20] = new State(-17);
    states[21] = new State(-32);
    states[22] = new State(new int[]{29,20,27,21,8,22},new int[]{-9,23,-8,30,-1,29,-2,19});
    states[23] = new State(new int[]{9,24,17,15,18,25});
    states[24] = new State(-33);
    states[25] = new State(new int[]{29,20,27,21,8,22},new int[]{-8,26,-1,29,-2,19});
    states[26] = new State(new int[]{19,17,20,27,17,-26,18,-26,21,-26,22,-26,23,-26,24,-26,7,-26,9,-26,25,-26});
    states[27] = new State(new int[]{29,20,27,21,8,22},new int[]{-1,28,-2,19});
    states[28] = new State(-29);
    states[29] = new State(-30);
    states[30] = new State(new int[]{19,17,20,27,17,-27,18,-27,21,-27,22,-27,23,-27,24,-27,7,-27,9,-27,25,-27});
    states[31] = new State(new int[]{29,20,27,21,8,22},new int[]{-9,32,-8,30,-1,29,-2,19});
    states[32] = new State(new int[]{17,15,18,25,21,-21,22,-21,23,-21,24,-21,7,-21,9,-21,25,-21});
    states[33] = new State(new int[]{29,20,27,21,8,22},new int[]{-9,34,-8,30,-1,29,-2,19});
    states[34] = new State(new int[]{17,15,18,25,21,-22,22,-22,23,-22,24,-22,7,-22,9,-22,25,-22});
    states[35] = new State(new int[]{29,20,27,21,8,22},new int[]{-9,36,-8,30,-1,29,-2,19});
    states[36] = new State(new int[]{17,15,18,25,21,-23,22,-23,23,-23,24,-23,7,-23,9,-23,25,-23});
    states[37] = new State(-20);
    states[38] = new State(new int[]{17,15,18,25,21,-24,22,-24,23,-24,24,-24,7,-24,9,-24,25,-24});
    states[39] = new State(-6);
    states[40] = new State(-7);
    states[41] = new State(new int[]{8,42});
    states[42] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-10,43,-9,38,-8,30,-1,29,-2,19});
    states[43] = new State(new int[]{9,44,21,13,22,31,23,33,24,35});
    states[44] = new State(new int[]{29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-4,45,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[45] = new State(-35);
    states[46] = new State(new int[]{29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-4,47,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[47] = new State(new int[]{5,48});
    states[48] = new State(new int[]{8,49});
    states[49] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-10,50,-9,38,-8,30,-1,29,-2,19});
    states[50] = new State(new int[]{9,51,21,13,22,31,23,33,24,35});
    states[51] = new State(new int[]{7,52});
    states[52] = new State(-36);
    states[53] = new State(-8);
    states[54] = new State(new int[]{8,55});
    states[55] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-10,56,-9,38,-8,30,-1,29,-2,19});
    states[56] = new State(new int[]{9,57,21,13,22,31,23,33,24,35});
    states[57] = new State(new int[]{29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-4,58,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[58] = new State(new int[]{11,59,4,-16,29,-16,3,-16,5,-16,16,-16,10,-16,12,-16,14,-16});
    states[59] = new State(new int[]{29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-4,60,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[60] = new State(-15);
    states[61] = new State(-9);
    states[62] = new State(new int[]{8,63});
    states[63] = new State(new int[]{29,20},new int[]{-3,64,-2,10});
    states[64] = new State(new int[]{7,65});
    states[65] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-10,66,-9,38,-8,30,-1,29,-2,19});
    states[66] = new State(new int[]{7,67,21,13,22,31,23,33,24,35});
    states[67] = new State(new int[]{29,20},new int[]{-3,68,-2,10});
    states[68] = new State(new int[]{9,69});
    states[69] = new State(new int[]{29,20,3,4,5,41,16,46,10,54,12,62,14,73},new int[]{-4,70,-3,8,-2,10,-7,39,-5,40,-11,53,-12,61,-13,71});
    states[70] = new State(-14);
    states[71] = new State(new int[]{7,72});
    states[72] = new State(-10);
    states[73] = new State(new int[]{25,74});
    states[74] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-14,75,-10,76,-9,38,-8,30,-1,29,-2,19});
    states[75] = new State(-13);
    states[76] = new State(new int[]{21,13,22,31,23,33,24,35,25,77,7,-11});
    states[77] = new State(new int[]{15,37,29,20,27,21,8,22},new int[]{-14,78,-10,76,-9,38,-8,30,-1,29,-2,19});
    states[78] = new State(-12);
    states[79] = new State(-3);

    rules[1] = new Rule(-16, new int[]{-15,2});
    rules[2] = new Rule(-15, new int[]{-7});
    rules[3] = new Rule(-6, new int[]{-4});
    rules[4] = new Rule(-6, new int[]{-6,-4});
    rules[5] = new Rule(-4, new int[]{-3,7});
    rules[6] = new Rule(-4, new int[]{-7});
    rules[7] = new Rule(-4, new int[]{-5});
    rules[8] = new Rule(-4, new int[]{-11});
    rules[9] = new Rule(-4, new int[]{-12});
    rules[10] = new Rule(-4, new int[]{-13,7});
    rules[11] = new Rule(-14, new int[]{-10});
    rules[12] = new Rule(-14, new int[]{-10,25,-14});
    rules[13] = new Rule(-13, new int[]{14,25,-14});
    rules[14] = new Rule(-12, new int[]{12,8,-3,7,-10,7,-3,9,-4});
    rules[15] = new Rule(-11, new int[]{10,8,-10,9,-4,11,-4});
    rules[16] = new Rule(-11, new int[]{10,8,-10,9,-4});
    rules[17] = new Rule(-2, new int[]{29});
    rules[18] = new Rule(-3, new int[]{-2,6,-10});
    rules[19] = new Rule(-10, new int[]{-10,21,-9});
    rules[20] = new Rule(-10, new int[]{15});
    rules[21] = new Rule(-10, new int[]{-10,22,-9});
    rules[22] = new Rule(-10, new int[]{-10,23,-9});
    rules[23] = new Rule(-10, new int[]{-10,24,-9});
    rules[24] = new Rule(-10, new int[]{-9});
    rules[25] = new Rule(-9, new int[]{-9,17,-8});
    rules[26] = new Rule(-9, new int[]{-9,18,-8});
    rules[27] = new Rule(-9, new int[]{-8});
    rules[28] = new Rule(-8, new int[]{-8,19,-1});
    rules[29] = new Rule(-8, new int[]{-8,20,-1});
    rules[30] = new Rule(-8, new int[]{-1});
    rules[31] = new Rule(-1, new int[]{-2});
    rules[32] = new Rule(-1, new int[]{27});
    rules[33] = new Rule(-1, new int[]{8,-9,9});
    rules[34] = new Rule(-7, new int[]{3,-6,4});
    rules[35] = new Rule(-5, new int[]{5,8,-10,9,-4});
    rules[36] = new Rule(-5, new int[]{16,-4,5,8,-10,9,7});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // progr -> block
{ root = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 3: // stlist -> statement
{ 
				CurrentSemanticValue.blVal = new BlockNode(ValueStack[ValueStack.Depth-1].stVal); 
			}
        break;
      case 4: // stlist -> stlist, statement
{ 
				ValueStack[ValueStack.Depth-2].blVal.Add(ValueStack[ValueStack.Depth-1].stVal); 
				CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal; 
			}
        break;
      case 5: // statement -> assign, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].stVal; }
        break;
      case 6: // statement -> block
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 7: // statement -> cycle
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 8: // statement -> cond
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].condVal as StatementNode; }
        break;
      case 9: // statement -> for_cycle
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].forVal as StatementNode; }
        break;
      case 10: // statement -> print_expr, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].printVal as StatementNode; }
        break;
      case 11: // print_expr_list -> bincond
{ CurrentSemanticValue.exprlVal = new ExprListNode(); CurrentSemanticValue.exprlVal.Add(ValueStack[ValueStack.Depth-1].bExprVal); }
        break;
      case 12: // print_expr_list -> bincond, SHIFT_LEFT, print_expr_list
{ CurrentSemanticValue.exprlVal.Add(ValueStack[ValueStack.Depth-3].bExprVal); }
        break;
      case 13: // print_expr -> COUT, SHIFT_LEFT, print_expr_list
{ CurrentSemanticValue.printVal = new PrintNode(ValueStack[ValueStack.Depth-1].exprlVal, false); }
        break;
      case 14: // for_cycle -> FOR, LEFT_R_BRACKET, assign, SEMICOLON, bincond, SEMICOLON, assign, 
               //              RIGHT_R_BRACKET, statement
{ CurrentSemanticValue.forVal = new ForCycleNode(ValueStack[ValueStack.Depth-7].stVal as AssignNode, ValueStack[ValueStack.Depth-5].bExprVal, ValueStack[ValueStack.Depth-3].stVal as AssignNode, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 15: // cond -> IF, LEFT_R_BRACKET, bincond, RIGHT_R_BRACKET, statement, ELSE, 
               //         statement
{ CurrentSemanticValue.condVal = new ConditionNode(ValueStack[ValueStack.Depth-5].bExprVal, ValueStack[ValueStack.Depth-3].stVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 16: // cond -> IF, LEFT_R_BRACKET, bincond, RIGHT_R_BRACKET, statement
{ CurrentSemanticValue.condVal = new ConditionNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].stVal, null); }
        break;
      case 17: // ident -> ID
{ CurrentSemanticValue.eVal = new IdNode(ValueStack[ValueStack.Depth-1].sVal); }
        break;
      case 18: // assign -> ident, ASSIGN, bincond
{ CurrentSemanticValue.stVal = new AssignNode(ValueStack[ValueStack.Depth-3].eVal as IdNode, ValueStack[ValueStack.Depth-1].bExprVal as ExprNode); }
        break;
      case 19: // bincond -> bincond, MORE, binsum
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].bExprVal, OperationType.More); }
        break;
      case 20: // bincond -> ENDL
{ CurrentSemanticValue.bExprVal = new BinExprNode(null, null, OperationType.Endl); }
        break;
      case 21: // bincond -> bincond, LESS, binsum
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].bExprVal, OperationType.Less); }
        break;
      case 22: // bincond -> bincond, MORE_EQUAL, binsum
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].bExprVal, OperationType.MoreEqual); }
        break;
      case 23: // bincond -> bincond, LESS_EQUAL, binsum
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].bExprVal, OperationType.LessEqual); }
        break;
      case 24: // bincond -> binsum
{ CurrentSemanticValue.bExprVal = ValueStack[ValueStack.Depth-1].bExprVal as BinExprNode; }
        break;
      case 25: // binsum -> binsum, PLUS, binmult
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].bExprVal, OperationType.Plus); }
        break;
      case 26: // binsum -> binsum, MINUS, binmult
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].bExprVal, OperationType.Minus); }
        break;
      case 27: // binsum -> binmult
{ CurrentSemanticValue.bExprVal = ValueStack[ValueStack.Depth-1].bExprVal as BinExprNode; }
        break;
      case 28: // binmult -> binmult, MULT, expr
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].eVal, OperationType.Mult); }
        break;
      case 29: // binmult -> binmult, DIV, expr
{ CurrentSemanticValue.bExprVal = new BinExprNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].eVal, OperationType.Div); }
        break;
      case 30: // binmult -> expr
{ CurrentSemanticValue.bExprVal = ValueStack[ValueStack.Depth-1].eVal as BinExprNode; }
        break;
      case 31: // expr -> ident
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal as IdNode; }
        break;
      case 32: // expr -> INUM
{ CurrentSemanticValue.eVal = new IntNumNode(ValueStack[ValueStack.Depth-1].iVal); }
        break;
      case 33: // expr -> LEFT_R_BRACKET, binsum, RIGHT_R_BRACKET
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-2].bExprVal as ExprNode; }
        break;
      case 34: // block -> BEGIN, stlist, END
{ CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal; }
        break;
      case 35: // cycle -> CYCLE, LEFT_R_BRACKET, bincond, RIGHT_R_BRACKET, statement
{ CurrentSemanticValue.stVal = new CycleNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-1].stVal, true); }
        break;
      case 36: // cycle -> DO, statement, CYCLE, LEFT_R_BRACKET, bincond, RIGHT_R_BRACKET, 
               //          SEMICOLON
{ CurrentSemanticValue.stVal = new CycleNode(ValueStack[ValueStack.Depth-3].bExprVal, ValueStack[ValueStack.Depth-6].stVal, false); }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


}
}
