// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  UNREAL-PC
// DateTime: 27.11.2015 1:57:22
// UserName: Vladislav
// Input file <SimpleYacc_C.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using ProgramTree;

namespace SimpleParserC
{
public enum Tokens {
    error=1,EOF=2,ASSIGN=3,SEMICOLON=4,PLUS=5,MINUS=6,
    MUL=7,DIV=8,LBRACKET=9,RBRACKET=10,BEGIN=11,END=12,
    IF=13,ELSE=14,WHILE=15,DO=16,LESS=17,GREAT=18,
    EQUAL=19,INEQUAL=20,LSHIFT=21,COUT=22,COMMA=23,COLON=24,
    NOT=25,LESSEQUAL=26,GREATEREQUAL=27,GOTO=28,INUM=29,RNUM=30,
    ID=31,STRING_L=32,TYPE=33};

public struct ValueType
{
			public double dVal;
			public int iVal;
			public string sVal;
			public Node nVal;
			public ExprNode eVal;
			public StatementNode stVal;
			public BlockNode blVal;
			public CoutNode ioVal;
			public FunctionNode funVal;
			public FunctionNodeSt funStVal;
			public List<ExprNode> paramVal;
			public SimpleVarType typeVal;
        }
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SimpleYacc_C.y
    public BlockNode root;
    public Parser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc_C.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[54];
  private static State[] states = new State[104];
  private static string[] nonTerms = new string[] {
      "expr", "ident", "T", "F", "S", "U", "assign", "statement", "st", "do_while", 
      "while", "if", "decl_assign", "goto", "stlist", "block", "cout", "funcall", 
      "funcallst", "params", "progr", "$accept", };

  static Parser() {
    states[0] = new State(new int[]{11,4},new int[]{-21,1,-16,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-15,5,-8,103,-2,8,-9,68,-7,11,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[5] = new State(new int[]{12,6,31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-8,7,-2,8,-9,68,-7,11,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[6] = new State(-51);
    states[7] = new State(-4);
    states[8] = new State(new int[]{24,9,3,14});
    states[9] = new State(new int[]{31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-9,10,-7,11,-2,13,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[10] = new State(-9);
    states[11] = new State(new int[]{4,12});
    states[12] = new State(-11);
    states[13] = new State(new int[]{3,14});
    states[14] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,15,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[15] = new State(new int[]{17,16,18,30,19,42,20,51,26,53,27,55,4,-26});
    states[16] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-5,17,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[17] = new State(new int[]{5,18,6,32,17,-28,18,-28,19,-28,20,-28,26,-28,27,-28,4,-28,10,-28,23,-28,21,-28});
    states[18] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-3,19,-6,45,-4,22,-2,23,-18,46});
    states[19] = new State(new int[]{7,20,8,34,5,-35,6,-35,17,-35,18,-35,19,-35,20,-35,26,-35,27,-35,4,-35,10,-35,23,-35,21,-35});
    states[20] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-6,21,-4,22,-2,23,-18,46});
    states[21] = new State(-38);
    states[22] = new State(-40);
    states[23] = new State(-43);
    states[24] = new State(new int[]{9,25,24,-25,3,-25,7,-25,8,-25,5,-25,6,-25,17,-25,18,-25,19,-25,20,-25,26,-25,27,-25,4,-25,10,-25,23,-25,21,-25});
    states[25] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-20,26,-1,58,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[26] = new State(new int[]{10,27,23,28});
    states[27] = new State(-24);
    states[28] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,29,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[29] = new State(new int[]{17,16,18,30,19,42,20,51,26,53,27,55,10,-8,23,-8});
    states[30] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-5,31,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[31] = new State(new int[]{5,18,6,32,17,-29,18,-29,19,-29,20,-29,26,-29,27,-29,4,-29,10,-29,23,-29,21,-29});
    states[32] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-3,33,-6,45,-4,22,-2,23,-18,46});
    states[33] = new State(new int[]{7,20,8,34,5,-36,6,-36,17,-36,18,-36,19,-36,20,-36,26,-36,27,-36,4,-36,10,-36,23,-36,21,-36});
    states[34] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-6,35,-4,22,-2,23,-18,46});
    states[35] = new State(-39);
    states[36] = new State(-44);
    states[37] = new State(-45);
    states[38] = new State(-46);
    states[39] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,40,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[40] = new State(new int[]{10,41,17,16,18,30,19,42,20,51,26,53,27,55});
    states[41] = new State(-47);
    states[42] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-5,43,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[43] = new State(new int[]{5,18,6,32,17,-30,18,-30,19,-30,20,-30,26,-30,27,-30,4,-30,10,-30,23,-30,21,-30});
    states[44] = new State(new int[]{7,20,8,34,5,-34,6,-34,17,-34,18,-34,19,-34,20,-34,26,-34,27,-34,4,-34,10,-34,23,-34,21,-34});
    states[45] = new State(-37);
    states[46] = new State(-48);
    states[47] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-6,48,-4,22,-2,23,-18,46});
    states[48] = new State(-41);
    states[49] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-6,50,-4,22,-2,23,-18,46});
    states[50] = new State(-42);
    states[51] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-5,52,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[52] = new State(new int[]{5,18,6,32,17,-31,18,-31,19,-31,20,-31,26,-31,27,-31,4,-31,10,-31,23,-31,21,-31});
    states[53] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-5,54,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[54] = new State(new int[]{5,18,6,32,17,-32,18,-32,19,-32,20,-32,26,-32,27,-32,4,-32,10,-32,23,-32,21,-32});
    states[55] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-5,56,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[56] = new State(new int[]{5,18,6,32,17,-33,18,-33,19,-33,20,-33,26,-33,27,-33,4,-33,10,-33,23,-33,21,-33});
    states[57] = new State(new int[]{5,18,6,32,17,-27,18,-27,19,-27,20,-27,26,-27,27,-27,4,-27,10,-27,23,-27,21,-27});
    states[58] = new State(new int[]{17,16,18,30,19,42,20,51,26,53,27,55,10,-7,23,-7});
    states[59] = new State(-12);
    states[60] = new State(new int[]{4,61});
    states[61] = new State(-13);
    states[62] = new State(new int[]{31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-8,63,-2,8,-9,68,-7,11,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[63] = new State(new int[]{15,64});
    states[64] = new State(new int[]{9,65});
    states[65] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,66,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[66] = new State(new int[]{10,67,17,16,18,30,19,42,20,51,26,53,27,55});
    states[67] = new State(-52);
    states[68] = new State(-10);
    states[69] = new State(-14);
    states[70] = new State(new int[]{9,71});
    states[71] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,72,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[72] = new State(new int[]{10,73,17,16,18,30,19,42,20,51,26,53,27,55});
    states[73] = new State(new int[]{31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-8,74,-2,8,-9,68,-7,11,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[74] = new State(-53);
    states[75] = new State(new int[]{4,76,21,77});
    states[76] = new State(-15);
    states[77] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,78,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[78] = new State(new int[]{17,16,18,30,19,42,20,51,26,53,27,55,4,-6,21,-6});
    states[79] = new State(new int[]{21,80});
    states[80] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,81,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[81] = new State(new int[]{17,16,18,30,19,42,20,51,26,53,27,55,4,-5,21,-5});
    states[82] = new State(-16);
    states[83] = new State(new int[]{9,84});
    states[84] = new State(new int[]{31,24,29,36,30,37,32,38,9,39,6,47,25,49},new int[]{-1,85,-5,57,-3,44,-6,45,-4,22,-2,23,-18,46});
    states[85] = new State(new int[]{10,86,17,16,18,30,19,42,20,51,26,53,27,55});
    states[86] = new State(new int[]{31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-8,87,-2,8,-9,68,-7,11,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[87] = new State(new int[]{14,88,12,-49,31,-49,11,-49,16,-49,15,-49,22,-49,13,-49,33,-49,28,-49});
    states[88] = new State(new int[]{31,24,11,4,16,62,15,70,22,79,13,83,33,95,28,101},new int[]{-8,89,-2,8,-9,68,-7,11,-16,59,-10,60,-11,69,-17,75,-12,82,-19,90,-18,92,-13,93,-14,99});
    states[89] = new State(-50);
    states[90] = new State(new int[]{4,91});
    states[91] = new State(-17);
    states[92] = new State(-23);
    states[93] = new State(new int[]{4,94});
    states[94] = new State(-18);
    states[95] = new State(new int[]{31,98},new int[]{-7,96,-2,97});
    states[96] = new State(-21);
    states[97] = new State(new int[]{3,14,4,-22});
    states[98] = new State(-25);
    states[99] = new State(new int[]{4,100});
    states[100] = new State(-19);
    states[101] = new State(new int[]{31,98},new int[]{-2,102});
    states[102] = new State(-20);
    states[103] = new State(-3);

    rules[1] = new Rule(-22, new int[]{-21,2});
    rules[2] = new Rule(-21, new int[]{-16});
    rules[3] = new Rule(-15, new int[]{-8});
    rules[4] = new Rule(-15, new int[]{-15,-8});
    rules[5] = new Rule(-17, new int[]{22,21,-1});
    rules[6] = new Rule(-17, new int[]{-17,21,-1});
    rules[7] = new Rule(-20, new int[]{-1});
    rules[8] = new Rule(-20, new int[]{-20,23,-1});
    rules[9] = new Rule(-8, new int[]{-2,24,-9});
    rules[10] = new Rule(-8, new int[]{-9});
    rules[11] = new Rule(-9, new int[]{-7,4});
    rules[12] = new Rule(-9, new int[]{-16});
    rules[13] = new Rule(-9, new int[]{-10,4});
    rules[14] = new Rule(-9, new int[]{-11});
    rules[15] = new Rule(-9, new int[]{-17,4});
    rules[16] = new Rule(-9, new int[]{-12});
    rules[17] = new Rule(-9, new int[]{-19,4});
    rules[18] = new Rule(-9, new int[]{-13,4});
    rules[19] = new Rule(-9, new int[]{-14,4});
    rules[20] = new Rule(-14, new int[]{28,-2});
    rules[21] = new Rule(-13, new int[]{33,-7});
    rules[22] = new Rule(-13, new int[]{33,-2});
    rules[23] = new Rule(-19, new int[]{-18});
    rules[24] = new Rule(-18, new int[]{31,9,-20,10});
    rules[25] = new Rule(-2, new int[]{31});
    rules[26] = new Rule(-7, new int[]{-2,3,-1});
    rules[27] = new Rule(-1, new int[]{-5});
    rules[28] = new Rule(-1, new int[]{-1,17,-5});
    rules[29] = new Rule(-1, new int[]{-1,18,-5});
    rules[30] = new Rule(-1, new int[]{-1,19,-5});
    rules[31] = new Rule(-1, new int[]{-1,20,-5});
    rules[32] = new Rule(-1, new int[]{-1,26,-5});
    rules[33] = new Rule(-1, new int[]{-1,27,-5});
    rules[34] = new Rule(-5, new int[]{-3});
    rules[35] = new Rule(-5, new int[]{-5,5,-3});
    rules[36] = new Rule(-5, new int[]{-5,6,-3});
    rules[37] = new Rule(-3, new int[]{-6});
    rules[38] = new Rule(-3, new int[]{-3,7,-6});
    rules[39] = new Rule(-3, new int[]{-3,8,-6});
    rules[40] = new Rule(-6, new int[]{-4});
    rules[41] = new Rule(-6, new int[]{6,-6});
    rules[42] = new Rule(-6, new int[]{25,-6});
    rules[43] = new Rule(-4, new int[]{-2});
    rules[44] = new Rule(-4, new int[]{29});
    rules[45] = new Rule(-4, new int[]{30});
    rules[46] = new Rule(-4, new int[]{32});
    rules[47] = new Rule(-4, new int[]{9,-1,10});
    rules[48] = new Rule(-4, new int[]{-18});
    rules[49] = new Rule(-12, new int[]{13,9,-1,10,-8});
    rules[50] = new Rule(-12, new int[]{13,9,-1,10,-8,14,-8});
    rules[51] = new Rule(-16, new int[]{11,-15,12});
    rules[52] = new Rule(-10, new int[]{16,-8,15,9,-1,10});
    rules[53] = new Rule(-11, new int[]{15,9,-1,10,-8});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // progr -> block
{ root = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 3: // stlist -> statement
{ CurrentSemanticValue.blVal = new BlockNode(ValueStack[ValueStack.Depth-1].stVal);	}
        break;
      case 4: // stlist -> stlist, statement
{
			ValueStack[ValueStack.Depth-2].blVal.Add(ValueStack[ValueStack.Depth-1].stVal);
			CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal;
		}
        break;
      case 5: // cout -> COUT, LSHIFT, expr
{ CurrentSemanticValue.ioVal = new CoutNode(ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 6: // cout -> cout, LSHIFT, expr
{
    		ValueStack[ValueStack.Depth-3].ioVal.Add(ValueStack[ValueStack.Depth-1].eVal);
    		CurrentSemanticValue.ioVal = ValueStack[ValueStack.Depth-3].ioVal;
    	}
        break;
      case 7: // params -> expr
{ CurrentSemanticValue.paramVal = new List<ExprNode>(); CurrentSemanticValue.paramVal.Add(ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 8: // params -> params, COMMA, expr
{
			ValueStack[ValueStack.Depth-3].paramVal.Add(ValueStack[ValueStack.Depth-1].eVal);
			CurrentSemanticValue.paramVal = ValueStack[ValueStack.Depth-3].paramVal;
		}
        break;
      case 9: // statement -> ident, COLON, st
{ ValueStack[ValueStack.Depth-1].stVal.AddLabel(ValueStack[ValueStack.Depth-3].eVal as IdNode); CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal;}
        break;
      case 10: // statement -> st
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 11: // st -> assign, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].stVal; }
        break;
      case 12: // st -> block
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 13: // st -> do_while, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].stVal; }
        break;
      case 14: // st -> while
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 15: // st -> cout, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].ioVal; }
        break;
      case 16: // st -> if
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 17: // st -> funcallst, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].funStVal; }
        break;
      case 18: // st -> decl_assign, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].stVal; }
        break;
      case 19: // st -> goto, SEMICOLON
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-2].stVal; }
        break;
      case 20: // goto -> GOTO, ident
{ CurrentSemanticValue.stVal = new GotoNode(ValueStack[ValueStack.Depth-1].eVal as IdNode); }
        break;
      case 21: // decl_assign -> TYPE, assign
{ CurrentSemanticValue.stVal = new VarDeclNode(ValueStack[ValueStack.Depth-2].typeVal, ValueStack[ValueStack.Depth-1].stVal as AssignNode); }
        break;
      case 22: // decl_assign -> TYPE, ident
{ CurrentSemanticValue.stVal = new VarDeclNode(ValueStack[ValueStack.Depth-2].typeVal, ValueStack[ValueStack.Depth-1].eVal as IdNode); }
        break;
      case 23: // funcallst -> funcall
{ CurrentSemanticValue.funStVal = new FunctionNodeSt(); CurrentSemanticValue.funStVal.Function = ValueStack[ValueStack.Depth-1].funVal; }
        break;
      case 24: // funcall -> ID, LBRACKET, params, RBRACKET
{
		CurrentSemanticValue.funVal = new FunctionNode(ValueStack[ValueStack.Depth-4].sVal);
		CurrentSemanticValue.funVal.Parameters = ValueStack[ValueStack.Depth-2].paramVal;
	}
        break;
      case 25: // ident -> ID
{ CurrentSemanticValue.eVal = new IdNode(ValueStack[ValueStack.Depth-1].sVal); }
        break;
      case 26: // assign -> ident, ASSIGN, expr
{ CurrentSemanticValue.stVal = new AssignNode(ValueStack[ValueStack.Depth-3].eVal as IdNode, ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 27: // expr -> S
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 28: // expr -> expr, LESS, S
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Less); }
        break;
      case 29: // expr -> expr, GREAT, S
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Greater); }
        break;
      case 30: // expr -> expr, EQUAL, S
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Equal); }
        break;
      case 31: // expr -> expr, INEQUAL, S
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.NotEqual); }
        break;
      case 32: // expr -> expr, LESSEQUAL, S
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.LessEqual); }
        break;
      case 33: // expr -> expr, GREATEREQUAL, S
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.GreaterEqual); }
        break;
      case 34: // S -> T
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 35: // S -> S, PLUS, T
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Plus); }
        break;
      case 36: // S -> S, MINUS, T
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Minus); }
        break;
      case 37: // T -> U
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 38: // T -> T, MUL, U
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Mult); }
        break;
      case 39: // T -> T, DIV, U
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].eVal, BinaryOperation.Div); }
        break;
      case 40: // U -> F
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 41: // U -> MINUS, U
{ CurrentSemanticValue.eVal = new UnaryNode(ValueStack[ValueStack.Depth-1].eVal, UnaryOperation.Minus); }
        break;
      case 42: // U -> NOT, U
{ CurrentSemanticValue.eVal = new UnaryNode(ValueStack[ValueStack.Depth-1].eVal, UnaryOperation.Not); }
        break;
      case 43: // F -> ident
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal as IdNode; }
        break;
      case 44: // F -> INUM
{ CurrentSemanticValue.eVal = new IntNumNode(ValueStack[ValueStack.Depth-1].iVal); }
        break;
      case 45: // F -> RNUM
{ CurrentSemanticValue.eVal = new FloatNumNode(ValueStack[ValueStack.Depth-1].dVal); }
        break;
      case 46: // F -> STRING_L
{ CurrentSemanticValue.eVal = new StringLiteralNode(ValueStack[ValueStack.Depth-1].sVal); }
        break;
      case 47: // F -> LBRACKET, expr, RBRACKET
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-2].eVal; }
        break;
      case 48: // F -> funcall
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].funVal; }
        break;
      case 49: // if -> IF, LBRACKET, expr, RBRACKET, statement
{ CurrentSemanticValue.stVal = new IfNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 50: // if -> IF, LBRACKET, expr, RBRACKET, statement, ELSE, statement
{ CurrentSemanticValue.stVal = new IfNode(ValueStack[ValueStack.Depth-5].eVal, ValueStack[ValueStack.Depth-3].stVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 51: // block -> BEGIN, stlist, END
{ CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal; }
        break;
      case 52: // do_while -> DO, statement, WHILE, LBRACKET, expr, RBRACKET
{ CurrentSemanticValue.stVal = new DoWhileNode(ValueStack[ValueStack.Depth-2].eVal, ValueStack[ValueStack.Depth-5].stVal); }
        break;
      case 53: // while -> WHILE, LBRACKET, expr, RBRACKET, statement
{ CurrentSemanticValue.stVal = new WhileNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
